version: '3'
services:

  mongodb:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      back_net:
        aliases:
          - mongodb

  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      back_net:
        aliases:
          - rabbitmq

  crawler:
    build: search_engine_crawler
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
      - RMQ_HOST=rabbitmq
      - RMQ_QUEUE=queue1
      - RMQ_USERNAME=user
      - RMQ_PASSWORD=password
      - CHECK_INTERVAL=60
      - EXCLUDE_URLS='.*github.com'
    command: python3 -u crawler/crawler.py https://vitkhab.github.io/search_engine_test_site/
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      back_net:
        aliases:
          - crawler
      front_net:
        aliases:
          - crawler      

  crawler-ui:
    build: search_engine_ui
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
      - FLASK_APP=ui.py
    depends_on:
      - mongodb
      - rabbitmq
      - crawler
    ports: 
      - "8000:8000/tcp"
    networks:
      back_net:
        aliases:
          - crawler-ui
      front_net:
        aliases:
          - crawler-ui

networks:
  back_net:
  front_net:

volumes:
  post_db:
