---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    component: mongodb
  namespace: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        component: mongodb
    spec:
      containers:
      - image: mongo:3.2
        name: mongodb
