---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crawler-ui
  labels:
    app: crawler
    component: ui
  namespace: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui
  template:
    metadata:
      name: crawler-ui
      labels:
        app: crawler
        component: ui
    spec:
      containers:
      - image: scoutjam/search_engine-crawler-ui:1.0
        name: ui
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_APP
          value: ui.py
