---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
  namespace: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
          - containerPort: 4369
          - containerPort: 5671
          - containerPort: 5672
          - containerPort: 15691
          - containerPort: 15692
          - containerPort: 25672
