apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
  namespace: search-engine
spec:
  type: ClusterIP
  ports:
    - name: port4369
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: port5671
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: port5672
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: port15691
      port: 15691
      protocol: TCP
      targetPort: 15691
    - name: port15692
      port: 15692
      protocol: TCP
      targetPort: 15692
    - name: port25672
      port: 25672
      protocol: TCP
      targetPort: 25672
  selector:
    component: rabbitmq
