name: Test Crawler
on: 
  push:
    paths:
      - 'submodule_updates/**'
      - 'compose.yaml'
      - 'update_and_move.sh'
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Run init script
        run: ./update_and_move.sh
        
      - name: Run docker compose
        run: docker compose up -d
        
      - name: Test ui
        run: docker exec --workdir /app search_engine-crawler-ui-1 python3 -m unittest discover -s tests/ 
        
