name: Test Crawler
on: workflow_dispatch
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run docker compose
        run: docker compose up -d
      - name: Process status
        run: docker compose ps -a
