name: Test Crawler
on: workflow_dispatch
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run init script
        run: ./update_and_move.sh
      - name: Run docker compose
        run: docker compose up -d
      - name: Process status
        run: docker compose ps -a
      - name: Test ui
        run: |
          docker exec -it search_engine-crawler-ui-1 sh
          cd ..
          python3 -m unittest discover -s tests/
        
